### ISSUE TITLE
hawaii-session -m nested doesn't work

### ISSUE THREAD

**Issue by n3rdopolis** [greenisland/greenisland#145]
I think it might be due to issues with greenisland not working on Weston's fullscreen-shell anymore, as manually calling the host Weston server, and calling hawaii on it results in a blank Weston screen, same as running
hawaii-sesion -m nested

Thanks

**Comment by plfiorini** [comment]
I will likely have time to take a look after I pushed the stuff I'm working on which requires doing some full screen shell work anyways.

**Comment by plfiorini** [comment]
I'm implementing #119 these days so this will be fixed as well.
With the new API things are more neat and separated: the greenisland QPA gained a wayland device integration for fullscreen shell. No windowed mode yet and crashes with more than one output.

**Comment by n3rdopolis** [comment]
I have tested this with the new hawaii and greenisland patches. It still seems like it doesn't display anything on a weston --shell=fullscreen-shell (or hawaii-session -m nested). unless I am missing an argument, or environment variable?

**Comment by plfiorini** [comment]
just tested: if I do ``hawaii-session -m nested`` on Xorg I can see a weston window with hawaii in it, if I do that on kms it doesn't work

**Comment by plfiorini** [comment]
Of course I have tested this on Xorg all the time :(

**Comment by plfiorini** [comment]
For the record when running hawaii-session -m nested it runs weston with fullscreen shell automatically but the hawaii process crashes.

**Comment by n3rdopolis** [comment]
Thanks for looking into this. To answer your question you asked on IRC, I do support the framebuffer in my distro.
 Since greenisland supports running on fullscreen-shell, and weston supports running on the Framebuffer, my waylandloginmanager script calls a weston supporting fullscreen shell on a TTY (using Weston's framebuffer backend if needed, and calling it with a different socket name to support multiple logins), and then tries to call Hawaii on that WAYLAND_DISPLAY.
Although, does greenisland support the framebuffer backend now?

**Comment by plfiorini** [comment]
Framebuffer: it used to support it back in 2012 with the original eglfs that was quiet different from the version I have forked to become the greenisland QPA plugin. I had it running on VirtualBox patching Mesa to add a fbdev backend took from Mer. I'm not sure whether it is avalable officially nowadays.
Basically it was a mix of eglfs default path (without hardware specific hooks) and EGL_PLATFORM=fbdev. It's something that I haven't look in a lot of time because distros usually do not have framebuffer enaled and do not build Mesa with fbdev support but since you have framebuffer enaled it can be considered as plan B. Plan A is to get fullscreen shell support working again which is way faster than fbdev.

**Comment by plfiorini** [comment]
As a reference: this might be related to this weston bug https://bugs.freedesktop.org/show_bug.cgi?id=93514

**Comment by plfiorini** [comment]
The old _wl_fullscreen_shell has been replaced with zwp_fullscreen_shell_v1 from wayland-protocols but I can't test because my weston supports only the former.

**Comment by plfiorini** [comment]
From IRC: now it shows something but crashes

http://pastebin.com/iEYgtDFT

**Comment by n3rdopolis** [comment]
More stacktraces with WAYLAND_DEBUG=client

http://pastebin.com/JrdmDxed
http://pastebin.com/dYSkmLvT
http://pastebin.com/U05f6MHC

**Comment by plfiorini** [comment]
Is this fixed with latest Weston?

**Comment by n3rdopolis** [comment]
still getting a crash. the stack trace seems different though...
I'm going to try to export the file

**Comment by n3rdopolis** [comment]
[gdb.txt](https://github.com/greenisland/greenisland/files/211804/gdb.txt)
